### ISSUE TITLE
Add in weapon transforms relative to the form

### ISSUE THREAD

**Issue by TinySandwich** [Moguri/prototype-mercury#107]
Dragon and Armor golems in particular are larger than the other golems, and when they hold weapons they look terrible.

If we could perform simple transformations for weapons that would help them look better when held.

**Comment by Moguri** [comment]
The conditions of satisfaction for this task is unclear to me, so I am leaving it open for now. I have added the ability to specify weapon transform offsets to forms. However, I have not updated any of the forms to use the new feature.

**Comment by Moguri** [comment]
Weapon offsets were used in #109 and seem to be sufficient for now.
