### ISSUE TITLE
Refine Job, Weapon, and Golem blender file structure

### ISSUE THREAD

**Issue by TinySandwich** [Moguri/prototype-mercury#71]
We need to figure out how we want to store all the different jobs, golems, and weapon combinations.

**Comment by TinySandwich** [comment]
Didn't you already do this? :)

**Comment by Moguri** [comment]
I still need to figure out if and where to move the golem meshes. However, now that jobs are going away, this is less urgent. So, maybe it's fine to close.

**Comment by Moguri** [comment]
No further changes are currently planned now that we no longer have a cartesian product of forms and jobs. Closing this issue.
