### ISSUE TITLE
EP system improvement

### ISSUE THREAD

**Issue by TinySandwich** [Moguri/prototype-mercury#73]
- [ ] The Golem's current EP # is not easily noticed, and so I kept running out of EP mid combat. I think, it should show the current and the total, over the curser when making an action/move.
- [x] When a unit rests, there should be some text that indicates so. Have it float up like the numbers. It was very confusing when sudden it was my turn again, and I didn't realize what happened.
- [x] I think the Armor Golem's EP of 4 is too low. They spend a lot of time resting.

**Comment by Moguri** [comment]
EP has been removed; closing this issue.
