### ISSUE TITLE
The Armor Golem is too easy to kite

### ISSUE THREAD

**Issue by TinySandwich** [Moguri/prototype-mercury#75]
The armor golem was designed as a tank, it's got the most HP and has very potent martial jobs. However, between it's reduced movement and EP amounts it is very easy for any golem to keep an Armor Golem at range without much recourse.

I've got a couple points and possible solutions I wish to pose to solve this issue.

1. Give all Golems the same speed value, but different EP. This would make the bigger, stronger golems tire more easily, but still letting them get in there.
2. Ranged attacks and magic have increased EP cost. This would force them to rest more often, letting melee combatants catch back up.
3. Ranged and magic attacks have decreased likelihood of hitting. This would make the melee combatants more likely to survive getting to melee.
4. Allow units to "run" or move double their speed. Doing so would be a general benefit and exacerbate the issue. So I was thinking "running" both decreases the Golem's toHit and toBeHit (making running Golems harder to be attacked and harder to attack. Ranged attacks would have to remain with range <6 for this to help with this issue.

**Comment by TinySandwich** [comment]
I think this one might be close able as well. As weapon abilities are being developed keep this in mind?

**Comment by TinySandwich** [comment]
Sorry, miss clicked.

**Comment by Moguri** [comment]
I agree
