### ISSUE TITLE
Tomb Golems are not viable at level 0

### ISSUE THREAD

**Issue by TinySandwich** [Moguri/prototype-mercury#80]
I'm not sure this is necessarily a bug, but Tomb Golems lack the HP and attack damage to win the first battle by themselves.

There's some ways we could fix this, though I'm open to suggestions :).

1) Improve the damage the Tomb Golem deals (then it's just a hitting match).
2) Figure out some way for "Sting and Move" to be viable.
3) Give the Tomb Golem some range to its base attacks.

**Comment by Moguri** [comment]
I am thinking we should close this and revisit this issue (if it still exists) after the weapons rework. Thoughts?

**Comment by TinySandwich** [comment]
Agreed!
