### ISSUE TITLE
Highlight attack ranges

### ISSUE THREAD

**Issue by TinySandwich** [Moguri/prototype-mercury#90]
It would be nice to see the weapon's basic attack range highlighted before moving.

**Comment by Moguri** [comment]
With #89 implemented, is this still relevant? Also, just to be clear, this is for highlighting the basic attack range while selecting a tile to move to, correct?

**Comment by Moguri** [comment]
One issue I am noticing, is we currently use the same color for showing range of movement as we do the range of an attack (blue in both cases).

**Comment by Moguri** [comment]
Fixed the color issue with da9905ea43d12ab3704f190a3008943b6c4bd486
